cmake_minimum_required(VERSION 3.20.0)

set(VAR_VARIABLE Variable)
set(VAR_TRUE TRUE)
set(VAR_FALSE FALSE)

message("VAR_VARIABLE: ")
if (VAR_VARIABLE)
  message(TRUE)
else()
  message(FALSE)
endif()

message("VAR_TRUE: ")
if (VAR_TRUE)
  message(TRUE)
else()
  message(FALSE)
endif()

message("VAR_FALSE: ")
if (VAR_FALSE)
  message(TRUE)
else()
  message(FALSE)
endif()

message("non empty string: ")
if ("non empty string")
  message(TRUE)
else()
  message(FALSE)
endif()

message("TRUE")
if ("TRUE")
  message(TRUE)
else()
  message(FALSE)
endif()

set(VAR1 FALSE)
set(VAR2 "VAR1")

if (${VAR2})
  message("var 2 is true i guess")
else()
  message("var 2 is not true i guess")
endif ()

set(FOO BAR)

if (FOO)
  message("foo is true i guess")
else()
  message("foo is not true i guess")
endif ()