cmake_minimum_required(VERSION 3.20.0)

function(MyFunction FirstArg)
  message("Function: ${CMAKE_CURRENT_FUNCTION}")
  message("Dir: ${CMAKE_CURRENT_FUNCTION_LIST_DIR}")
  message("File: ${CMAKE_CURRENT_FUNCTION_LIST_FILE}")
  message("Line: ${CMAKE_CURRENT_FUNCTION_LIST_LINE}")
  message("FirstArg: ${FirstArg}")
  set(FirstArg "new value")
  message("FirstArg again: ${FirstArg}")
  message("ARGV0: ${ARGV0} ARGV1: ${ARGV1} ARGC: ${ARGC}")
endfunction()

set(FirstArg "first value")
MyFunction("Value1" "Value2")
message("FirstArg in global scope: ${FirstArg}")
